Merge branch 'fix_mobilenetv1' into 'master'
Fix fcCell in MobilenetV1

## Context

The MobileNetV1 model shows inconsistency between FC input neurons number and the previous layer (for alpha = 0.1)

## Issue

The MobileNetV1 model was not consistent, the FC layers had input numbers different from output of previous cell, especially for low alpha values

```
Traceback (most recent call last):
  File "MobileNet.py", line 60, in <module>
    model = model.to_deepnet_cell(provider)
  File "/nvme1/is154584/fa125436/N2D2/n2d2-ip/N2D2/python/n2d2/cells/cell.py", line 300, in to_deepnet_cell
    dummy_output = self(dummy_input)
  File "/nvme1/is154584/fa125436/N2D2/n2d2-ip/N2D2/python/n2d2/cells/cell.py", line 279, in __call__
    x = cell(x)
  File "/nvme1/is154584/fa125436/N2D2/n2d2-ip/N2D2/python/n2d2/cells/cell.py", line 279, in __call__
    x = cell(x)
  File "/nvme1/is154584/fa125436/N2D2/n2d2-ip/N2D2/python/n2d2/cells/nn.py", line 514, in __call__
    self._add_to_graph(inputs)
  File "/nvme1/is154584/fa125436/N2D2/n2d2-ip/N2D2/python/n2d2/cells/nn.py", line 272, in _add_to_graph
    self.add_input(inputs)
  File "/nvme1/is154584/fa125436/N2D2/n2d2-ip/N2D2/python/n2d2/cells/nn.py", line 265, in add_input
    self._N2D2_object.initializeDataDependent()
RuntimeError: Unmatching dimensions X*Y*Z between input and weight tensor 0 for cell fc
```

## Solution

Changed in the file MobileNetV1.py, in `class MobileNetv1Head`:

`fc = Fc(32 * int(32 * alpha), nb_outputs, activation=Linear(), weights_filler=Normal(mean=0.0, std_dev=0.01)`

replaced by:

```
compute_nb_outputs = lambda x: int(x * 32 * alpha)
fc = Fc(compute_nb_outputs(32), nb_outputs, activation=Linear(), weights_filler=Normal(mean=0.0, std_dev=0.01)
```